# Change these first
owner: pauliver # Your GitHub username
repo: xbox-uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Microsoft Docs
    url: https://developer.microsoft.com/en-us/
  - name: Partner Docs 
    url: http://developer.microsoft.com/games/xbox/partner
  - name: Partner Docs (English)
    url: https://developer.microsoft.com/en-us/games/xbox/partner/
  - name: Forums
    url: https://forums.xboxlive.com/index.html
  - name: Download Center
    url: https://www.microsoft.com/en-us/software-download/gdk#section_GameCore
  - name: xbox game landing
    url: https://docs.microsoft.com/en-us/gaming/xbox/
  - name: redirector for xHub
    url: https://aka.ms/xhub


status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /xbox-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Testing uptime validator - back and setup again when docs are public
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
